# Generated by Django 5.2.1 on 2025-05-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0003_alter_drop_options_alter_drop_slug'),
        ('product', '0002_remove_product_iamge_product_drop_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='drop.drop'),
        ),
    ]
