# Generated by Django 5.2.1 on 2025-05-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0007_alter_drop_hero_video'),
        ('product', '0004_product_discount_product_is_available_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='drop.drop'),
        ),
    ]
