# Generated by Django 5.2.1 on 2025-05-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_detail_product_description_alter_product_drop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
