# Generated by Django 5.2.1 on 2025-06-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
    ]
