# Generated by Django 5.2.1 on 2025-05-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('names', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('last_names', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('image', models.ImageField(max_length=200, upload_to='perfil/', verbose_name='Imagenn de perfil')),
                ('active_user', models.BooleanField(default=True)),
                ('admin_user', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
