# Generated by Django 5.2.1 on 2025-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_names',
            field=models.CharField(default='No last names', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='names',
            field=models.CharField(default='No Names', max_length=150),
        ),
    ]
