# Generated by Django 5.2.1 on 2025-05-15 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('biography', models.TextField()),
                ('profile_image', models.ImageField(upload_to='designers/profile/')),
                ('cover_image', models.ImageField(upload_to='designers/cover/')),
                ('video_url', models.URLField(blank=True, help_text="URL to designer's featured video")),
                ('featured_in', models.TextField(blank=True, help_text='Publications/features, one per line')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer_profile', to='user.customuser')),
            ],
            options={
                'ordering': ['-is_verified', '-created_at'],
            },
        ),
    ]
