# Generated by Django 5.2.1 on 2025-05-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerprofile',
            name='featured_in',
            field=models.TextField(blank=True, help_text='Publicaciones o medios destacados (uno por línea)'),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL del video destacado'),
        ),
    ]
