# Generated by Django 5.2.1 on 2025-05-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_alter_designerprofile_featured_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='cover_image',
            field=models.ImageField(upload_to='talents/cover/'),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='profile_image',
            field=models.ImageField(upload_to='talents/profile/'),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL del video documental o presentación'),
        ),
    ]
