# Generated by Django 5.2.1 on 2025-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_designerprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='full_name',
            field=models.CharField(default='No name', max_length=100),
        ),
    ]
