# Generated by Django 5.2.1 on 2025-05-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_remove_designerprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
    ]
