# Generated by Django 5.2.1 on 2025-05-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_designerprofile_facebook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
