# Generated by Django 5.2.1 on 2025-06-22 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('biography', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(upload_to='talents/profile/')),
                ('video_url', models.URLField(blank=True, help_text='Video de presentación/documental')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_verified', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('website', 'Website'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('otro', 'Otro')], max_length=20)),
                ('url', models.URLField()),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='talent.talent')),
            ],
        ),
    ]
