# Generated by Django 5.2.1 on 2025-06-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_remove_talent_years_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='talents/cover/'),
        ),
    ]
