# Generated by Django 5.2.1 on 2025-05-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('launch_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='drops/cover/')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='drops/videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('social_impact', models.TextField(help_text='How this drop supports the community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designers', models.ManyToManyField(related_name='drops', to='designer.designerprofile')),
            ],
            options={
                'ordering': ['-launch_date'],
            },
        ),
    ]
