# Generated by Django 5.2.1 on 2025-06-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('drop_number', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='drops/cover/')),
                ('hero_video', models.URLField(blank=True, help_text='URL del video documental o presentación', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ManyToManyField(related_name='drops', to='talent.talent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
