# Generated by Django 5.2.1 on 2025-05-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drop',
            options={},
        ),
        migrations.AddField(
            model_name='drop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='social_impact',
            field=models.TextField(help_text='Cómo este drop apoya a la comunidad'),
        ),
    ]
