# Generated by Django 5.2.1 on 2025-05-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0002_alter_drop_options_drop_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drop',
            options={'ordering': ['-launch_date']},
        ),
        migrations.AlterField(
            model_name='drop',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
