# Generated by Django 5.2.1 on 2025-05-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0004_rename_theme_drop_drop_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='drop_number',
            field=models.IntegerField(),
        ),
    ]
