# Generated by Django 5.2.1 on 2025-05-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0005_alter_drop_drop_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='drop_number',
            field=models.CharField(max_length=100),
        ),
    ]
