# Generated by Django 5.2.1 on 2025-05-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0006_alter_drop_drop_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='hero_video',
            field=models.URLField(blank=True, help_text='URL del video documental o presentación', null=True),
        ),
    ]
