# Generated by Django 5.2.1 on 2025-05-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0007_alter_drop_hero_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drop',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='drop',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='drop',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='drop',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='drop',
            name='social_impact',
        ),
        migrations.AlterField(
            model_name='drop',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
